import { Header } from "@/components/Header";

export const metadata = {
  title: "Terms of Service — NativeFlow",
  description: "Terms covering free and Pro tiers, fair use, and subscriptions.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#faf8f5] dark:bg-[#09090b] text-[#1d1d1f] dark:text-[#f5f5f7]">
      <Header />
      <main className="max-w-2xl mx-auto px-5 pt-24 pb-20">

        <h1 className="text-2xl font-semibold mb-2">Terms of Service</h1>
        <p className="text-sm text-[#86868b] mb-10">Last updated: March 2026</p>

        <div className="border-t border-black/[0.06] dark:border-white/[0.06]" />

        <section className="mt-8">
          <p className="text-xs uppercase tracking-widest font-semibold text-[#86868b] mb-3">
            Acceptance
          </p>
          <p className="text-sm text-[#3d3d3f] dark:text-[#aeaeb2] leading-relaxed">
            By using NativeFlow, you agree to these terms. If you don&apos;t agree, please don&apos;t use the service. NativeFlow is operated by PolyGot Ltd, registered in England and Wales.
          </p>
        </section>

        <section className="mt-8">
          <p className="text-xs uppercase tracking-widest font-semibold text-[#86868b] mb-3">
            Free tier
          </p>
          <p className="text-sm text-[#3d3d3f] dark:text-[#aeaeb2] leading-relaxed">
            The free tier gives you 10 phrase checks per day, tracked by IP address. No account is required. We may adjust free-tier limits with reasonable notice. The free tier is provided as-is with no guarantees of availability.
          </p>
        </section>

        <section className="mt-8">
          <p className="text-xs uppercase tracking-widest font-semibold text-[#86868b] mb-3">
            Pro tier
          </p>
          <p className="text-sm text-[#3d3d3f] dark:text-[#aeaeb2] leading-relaxed">
            Pro is a paid subscription billed monthly or annually through Stripe. You can cancel at any time from your account settings. Cancellation takes effect at the end of your current billing period — you keep access until then. We don&apos;t offer refunds for partial billing periods, except where required by UK consumer law. Price changes will be notified at least 30 days in advance.
          </p>
        </section>

        <section className="mt-8">
          <p className="text-xs uppercase tracking-widest font-semibold text-[#86868b] mb-3">
            Fair use
          </p>
          <p className="text-sm text-[#3d3d3f] dark:text-[#aeaeb2] leading-relaxed">
            NativeFlow is for personal language learning. You may not use it for automated querying, bulk processing, scraping, or reselling results. Accounts that abuse the service — including attempts to circumvent rate limits — may be suspended without notice.
          </p>
        </section>

        <section className="mt-8">
          <p className="text-xs uppercase tracking-widest font-semibold text-[#86868b] mb-3">
            AI-generated content
          </p>
          <p className="text-sm text-[#3d3d3f] dark:text-[#aeaeb2] leading-relaxed">
            Results are generated by Claude AI (Anthropic) and are provided for guidance only. Language is subjective and regional — NativeFlow gives you an informed opinion, not a definitive verdict. We don&apos;t guarantee accuracy, and results should not be relied upon for professional, legal, medical, or safety-critical contexts.
          </p>
        </section>

        <section className="mt-8">
          <p className="text-xs uppercase tracking-widest font-semibold text-[#86868b] mb-3">
            Availability
          </p>
          <p className="text-sm text-[#3d3d3f] dark:text-[#aeaeb2] leading-relaxed">
            We aim for high availability but do not guarantee uptime. There is no SLA on the free tier. We may carry out maintenance or updates that temporarily affect availability — we&apos;ll aim to minimise disruption.
          </p>
        </section>

        <section className="mt-8">
          <p className="text-xs uppercase tracking-widest font-semibold text-[#86868b] mb-3">
            Accounts
          </p>
          <p className="text-sm text-[#3d3d3f] dark:text-[#aeaeb2] leading-relaxed">
            You&apos;re responsible for keeping your account credentials secure. Subscriptions are for one person — sharing access is not permitted. If you think your account has been compromised, contact us immediately at{" "}
            <a href="mailto:hello@polygot.com" className="text-indigo-500 hover:text-indigo-400 transition-colors">
              hello@polygot.com
            </a>
            .
          </p>
        </section>

        <section className="mt-8">
          <p className="text-xs uppercase tracking-widest font-semibold text-[#86868b] mb-3">
            Termination
          </p>
          <p className="text-sm text-[#3d3d3f] dark:text-[#aeaeb2] leading-relaxed">
            We may suspend or terminate access for accounts that violate these terms, without prior notice in serious cases. If you believe a suspension was made in error, contact us and we&apos;ll review it.
          </p>
        </section>

        <section className="mt-8">
          <p className="text-xs uppercase tracking-widest font-semibold text-[#86868b] mb-3">
            Governing law
          </p>
          <p className="text-sm text-[#3d3d3f] dark:text-[#aeaeb2] leading-relaxed">
            These terms are governed by the laws of England and Wales. Any disputes will be subject to the exclusive jurisdiction of the courts of England and Wales.
          </p>
        </section>

        <div className="border-t border-black/[0.06] dark:border-white/[0.06] mt-10 pt-8">
          <p className="text-sm text-[#3d3d3f] dark:text-[#aeaeb2] leading-relaxed">
            Questions about these terms?{" "}
            <a
              href="mailto:hello@polygot.com"
              className="text-indigo-500 hover:text-indigo-400 transition-colors"
            >
              hello@polygot.com
            </a>
          </p>
        </div>

      </main>
    </div>
  );
}
